// Maps every Google "Material Symbols Outlined" ligature name used in
// ui.html (grep for `material-symbols-outlined` there) to its
// @expo/vector-icons equivalent. Audited against MaterialIcons.json /
// MaterialCommunityIcons.json — only three names (chess_pawn, skull, swords)
// don't exist in classic Material Icons and fall back to
// MaterialCommunityIcons (swords -> "sword-cross", the closest glyph).
//
// Classic Material Icons has no FILL-axis variable-font toggle the way
// Material Symbols does — ui.html's outline/filled distinction is dropped
// here (all icons render as their single available glyph); revisit per-icon
// if a screen visually depends on the filled variant.

export type IconSet = "material" | "community";

export const ICONS: Record<string, { set: IconSet; name: string }> = {
  account_circle: { set: "material", name: "account-circle" },
  add_circle: { set: "material", name: "add-circle" },
  analytics: { set: "material", name: "analytics" },
  arrow_back: { set: "material", name: "arrow-back" },
  arrow_forward: { set: "material", name: "arrow-forward" },
  arrow_forward_ios: { set: "material", name: "arrow-forward-ios" },
  arrow_expand_horizontal: { set: "community", name: "arrow-expand-horizontal" },
  bolt: { set: "material", name: "bolt" },
  build: { set: "material", name: "build" },
  calendar_today: { set: "material", name: "calendar-today" },
  call_split: { set: "material", name: "call-split" },
  campaign: { set: "material", name: "campaign" },
  casino: { set: "material", name: "casino" },
  chat: { set: "material", name: "chat" },
  check: { set: "material", name: "check" },
  check_circle: { set: "material", name: "check-circle" },
  chess_king: { set: "community", name: "chess-king" },
  chess_pawn: { set: "community", name: "chess-pawn" },
  chevron_left: { set: "material", name: "chevron-left" },
  chevron_right: { set: "material", name: "chevron-right" },
  close: { set: "material", name: "close" },
  content_copy: { set: "material", name: "content-copy" },
  content_paste: { set: "material", name: "content-paste" },
  diamond: { set: "material", name: "diamond" },
  edit: { set: "material", name: "edit" },
  emoji_events: { set: "material", name: "emoji-events" },
  extension: { set: "material", name: "extension" },
  flag: { set: "material", name: "flag" },
  grid_4x4: { set: "material", name: "grid-4x4" },
  group: { set: "material", name: "group" },
  handshake: { set: "material", name: "handshake" },
  help: { set: "material", name: "help" },
  home: { set: "material", name: "home" },
  leaderboard: { set: "material", name: "leaderboard" },
  shopping_cart: { set: "material", name: "shopping-cart" },
  local_fire_department: { set: "material", name: "local-fire-department" },
  local_play: { set: "material", name: "local-play" },
  lock: { set: "material", name: "lock" },
  logout: { set: "material", name: "logout" },
  mail: { set: "material", name: "mail" },
  mark_email_read: { set: "material", name: "mark-email-read" },
  meeting_room: { set: "material", name: "meeting-room" },
  menu: { set: "material", name: "menu" },
  menu_book: { set: "material", name: "menu-book" },
  military_tech: { set: "material", name: "military-tech" },
  monetization_on: { set: "material", name: "monetization-on" },
  more_vert: { set: "material", name: "more-vert" },
  music_note: { set: "material", name: "music-note" },
  notifications: { set: "material", name: "notifications" },
  pan_tool: { set: "material", name: "pan-tool" },
  person: { set: "material", name: "person" },
  person_add: { set: "material", name: "person-add" },
  play_arrow: { set: "material", name: "play-arrow" },
  play_circle: { set: "material", name: "play-circle" },
  push_pin: { set: "material", name: "push-pin" },
  redeem: { set: "material", name: "redeem" },
  replay: { set: "material", name: "replay" },
  report: { set: "material", name: "report" },
  schedule: { set: "material", name: "schedule" },
  search: { set: "material", name: "search" },
  send: { set: "material", name: "send" },
  settings: { set: "material", name: "settings" },
  share: { set: "material", name: "share" },
  skip_next: { set: "material", name: "skip-next" },
  skip_previous: { set: "material", name: "skip-previous" },
  skull: { set: "community", name: "skull" },
  smart_toy: { set: "material", name: "smart-toy" },
  sports_esports: { set: "material", name: "sports-esports" },
  star: { set: "material", name: "star" },
  stars: { set: "material", name: "stars" },
  style: { set: "material", name: "style" },
  support_agent: { set: "material", name: "support-agent" },
  swords: { set: "community", name: "sword-cross" },
  thumb_up: { set: "material", name: "thumb-up" },
  timer: { set: "material", name: "timer" },
  toll: { set: "material", name: "toll" },
  trending_down: { set: "material", name: "trending-down" },
  trending_up: { set: "material", name: "trending-up" },
  upgrade: { set: "material", name: "upgrade" },
  verified: { set: "material", name: "verified" },
  visibility: { set: "material", name: "visibility" },
  volume_up: { set: "material", name: "volume-up" },
  warning: { set: "material", name: "warning" },
  workspace_premium: { set: "material", name: "workspace-premium" },
};
