const fs = require('fs');
const path = require('path');
const { withDangerousMod, withAppBuildGradle } = require('@expo/config-plugins');

// android/ is gitignored and fully regenerated by `npx expo prebuild`, so a
// hand-edit to android/app/build.gradle would be wiped out on the next
// prebuild -- this plugin reapplies it every time, the same way
// expo-build-properties already patches generated Android config today.
//
// Sources the real upload keystore from the repo root (release.jks +
// keystore.properties, both gitignored -- see .gitignore's comment) rather
// than from inside android/, since that's the one location guaranteed to
// survive regeneration. Gracefully falls back to the debug keystore when
// those files aren't present (a fresh clone without the secrets, CI, etc.)
// instead of hard-failing the build.
function withReleaseKeystoreFiles(config) {
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const platformRoot = config.modRequest.platformProjectRoot; // .../android

      const srcJks = path.join(projectRoot, 'release.jks');
      const srcProps = path.join(projectRoot, 'keystore.properties');

      if (fs.existsSync(srcJks)) {
        fs.copyFileSync(srcJks, path.join(platformRoot, 'app', 'release.jks'));
      }
      if (fs.existsSync(srcProps)) {
        fs.copyFileSync(srcProps, path.join(platformRoot, 'keystore.properties'));
      }

      return config;
    },
  ]);
}

function withReleaseSigningConfig(config) {
  return withAppBuildGradle(config, (config) => {
    let contents = config.modResults.contents;

    // Load keystore.properties (copied in by withReleaseKeystoreFiles above)
    // right before the `android {` block, matching the standard React
    // Native community pattern for local (non-EAS) release signing.
    const loaderSnippet = `
def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
def hasReleaseKeystore = keystorePropertiesFile.exists()
if (hasReleaseKeystore) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

`;
    if (!contents.includes('hasReleaseKeystore')) {
      contents = contents.replace(/\nandroid \{/, `${loaderSnippet}android {`);
    }

    // Add a `release` signingConfig alongside the existing `debug` one.
    const debugSigningConfigBlock = `signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }`;
    const withReleaseSigningConfigBlock = `signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        if (hasReleaseKeystore) {
            release {
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
    }`;
    if (contents.includes(debugSigningConfigBlock)) {
      contents = contents.replace(debugSigningConfigBlock, withReleaseSigningConfigBlock);
    }

    // Point the release buildType at the real keystore when present, falling
    // back to the debug key otherwise (never a hard failure).
    contents = contents.replace(
      /release \{\s*\n(\s*)\/\/ Caution!.*\n(\s*)\/\/ see https:\/\/reactnative\.dev\/docs\/signed-apk-android\.\n(\s*)signingConfig signingConfigs\.debug/,
      `release {\n$1// Caution! In production, you need to generate your own keystore file.\n$2// see https://reactnative.dev/docs/signed-apk-android.\n$3signingConfig hasReleaseKeystore ? signingConfigs.release : signingConfigs.debug`,
    );

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = function withReleaseKeystore(config) {
  config = withReleaseKeystoreFiles(config);
  config = withReleaseSigningConfig(config);
  return config;
};
